---
language: python
python:
  - '3.5'
  - '2.7'
before_install:
  - psql -c 'create database froide;' -U postgres
  - phantomjs --version
  - phantomjs --webdriver= &
install:
  - pip install -r requirements-test.txt
  - pip install psycopg2 coveralls
  - pip install -e .
script:
  - export DATABASE_URL=postgres://postgres@127.0.0.1/froide
  - make test
after_success:
  - coveralls
